### ISSUE TITLE
1곡만 있는 차트에 51위~n위 버튼이 표시됨

### ISSUE THREAD

**Issue by JellyBrick** [wakboardoo/libre-billboardoo-frontend#2]
https://github.com/wakboardoo/libre-billboardoo-frontend/blob/e1fd3db34cba47efc6e7dafadb1234de3dcc20ee/app/routes/rank/new.tsx#L61-L67

- 이미 관련 처리가 완료되어있으나, 정상적으로 동작하지 않음.
- 원인 파악 필요

**Comment by NeuroWhAI** [comment]
안녕하세요.
잠깐 봤는데 해당 부분은 스크롤 내렸을 때 상단에 붙어있는 버튼 쪽이고
그게 아닐 땐 아래 코드로 표시하는 것 같습니다.
https://github.com/wakboardoo/libre-billboardoo-frontend/blob/e1fd3db34cba47efc6e7dafadb1234de3dcc20ee/app/routes/rank/new.tsx#L76-L79
둘 다 관련 처리가 있어야 하지 않을까요.

**Comment by JellyBrick** [comment]
> 안녕하세요. 잠깐 봤는데 해당 부분은 스크롤 내렸을 때 상단에 붙어있는 버튼 쪽이고 그게 아닐 땐 아래 코드로 표시하는 것 같습니다.
> 
> https://github.com/wakboardoo/libre-billboardoo-frontend/blob/e1fd3db34cba47efc6e7dafadb1234de3dcc20ee/app/routes/rank/new.tsx#L76-L79
> 
> 둘 다 관련 처리가 있어야 하지 않을까요. ~아님 말고요.~

확인했습니다! 감사합니다~
